apiVersion: apps/v1
kind: Deployment
metadata:
  name: javacalc-deployment
  labels: 
    app: javacalc-app
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: javacalc
        image: aravindhmanyam/calc
        ports:
        - containerPort: 8080
