---
- name: git repo
  hosts: kops-workstation
  tasks: 
    - name: get code
      shell: |
        sudo git clone https://github.com/manyamaravindh/project.git
        cd project
        kubectl apply -f app.yml
...
