---
- name: git repo
  hosts: kops-workstation
  become: yes
  tasks: 
    - name: get code
      shell: |
        git clone https://github.com/manyamaravindh/project.git
        cd project
        kubectl apply -f app.yml
...
