---
- name: installations for Java Devops 
  hosts: server
  become: yes
  tasks:
  - name: basic installations
    yum:
      name:
        - vim
        - wget
        - git
        - java-1.8.0*
        - unzip
      state: present
  - name: install maven
    yum:
      name: maven
      state: present
  - name: install sonarqube
    get_url:
    become: no
      url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.7.zip
      dest: /home/centos/
      become: no
  - name: unzip sonar
    unarchive:
    become: no
      src: /home/centos/sonarqube-6.7.7.zip
      dest: /home/centos/
      remote_src: True
  - name: start Sonar port -9000
    shell: /home/centos/sonarqube-6.7.7/bin/linux-x86-64/sonar.sh start || /home/centos/sonarqube-6.7.7/bin/linux-x86-64/sonar.sh status 
    become: no
  - name: install docker
    shell: |
      curl -fsSL https://get.docker.com -o get-docker.sh
      sh get-docker.sh
      sudo usermod -aG docker centos
  - name:
    service:
      name: docker
      enabled: yes
      state: started
...
