---
- name: installations for Java Devops 
  hosts: server
  become: yes
  tasks:
  - name: basic installations
    yum:
      name:
        - vim
        - wget
        - git
        - java-1.8.0*
        - unzip
      state: present
  - name: install maven
    yum:
      name: maven
      state: present
  - name: install sonarqube
    become: no
    get_url:
      url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.7.zip
      dest: /home/centos/
  - name: unzip sonar
    become: no
    unarchive:
      src: /home/centos/sonarqube-6.7.7.zip
      dest: /home/centos/
      remote_src: True
  - name: start Sonar port -9000
    become: no
    shell: /home/centos/sonarqube-6.7.7/bin/linux-x86-64/sonar.sh start || /home/centos/sonarqube-6.7.7/bin/linux-x86-64/sonar.sh status 
- name: 
  hosts: server
  vars_prompt: 
    - name: "sonar url"
      prompt: "please enter sonarqube ip address"
      private: no
    - name: "sonar command"
      prompt: "loin with admin and admin as credentials and generate the mvn command and paste it below"
      private: no
  tasks:
  - name: download nexus
    get_url:
      url: https://download.sonatype.com/nexus/oss/nexus-2.14.18-01-bundle.tar.gz
      dest: /home/centos
    become: no
  - name: unzip nexus
    unarchive:
      src: /home/centos/nexus-2.14.18-01-bundle.tar.gz
      dest: /home/centos
      remote_src: yes
    become: no
  - name: start nexus port -8081/nexus
    shell: "/home/centos/nexus-2.14.18-01/bin/nexus start || /home/centos/nexus-2.14.18-01/bin/nexus status "
    become: no
  - name: download tomcat
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz
      dest: /home/centos
    become: no
  - name: extract tomcat
    unarchive: 
      src: /home/centos/apache-tomcat-7.0.94.tar.gz
      dest: /home/centos
      remote_src: yes
    become: no
  - name: start tomcat
    shell: cd apache-tomcat-7.0.94/bin || ./startup.sh
    become: no
  - name: install docker
    yum:
      name: docker
      state: present
    become: yes
  - name: Start docker
    service:
      name: docker
      enabled: yes
      state: started
...
