---
- name: installations for Java Devops 
  hosts: server
  become: yes
  tasks:
  - name: basic installations
    yum:
      name:
        - vim
        - wget
        - git
        - java-1.8.0*
        - unzip
      state: present
  - name: install maven
    yum:
      name: maven
      state: present
  - name: install docker
    shell: |
      curl -fsSL https://get.docker.com -o get-docker.sh
      sh get-docker.sh
      sudo usermod -aG docker centos
  - name:
    service:
      name: docker
      enabled: yes
      state: restarted
...
