---
- name: installations for Java Devops 
  hosts: server
  become: yes
  tasks:
  - name: basic installations
    yum:
      name:
        - vim
        - wget
        - git
        - java-1.8.0*
        - unzip
      state: present
  - name: install maven
    yum:
      name: maven
      state: present 
...
